language: elixir
sudo: false
elixir:
- 1.3.2
otp_release:
- 18.0
- 19.0
after_script:
- mix deps.get --only docs
- MIX_ENV=docs mix inch.report
deploy:
  provider: script
  script: scripts/hex.sh
  on:
    tags: true
    otp_release: 19.0
    repo: jeffutter/particle-elixir
env:
  global:
    secure: j0fh5RYsYKZsIzxEmcQ/c0yMNtPh54HAENAi98grnqGi/HbuygCzfIC5rI5mFz4F6f4Csx+Mbs2x5pmQOoJke3e0NfXua9ohi5dqgV9gZ5IeiCUsHZj+HZaY/p9caVivyb0xH8BiuOOl8d4LQCUrO8eGYBUaNIhw9j1/mWgRrK4iKh+aB7xiMNAg114fvfJye4K1QlYxFC7j/+u3OWWKl5pV4lDIqG5jVdO1lwtKIrDjR4DlSsCPd7Ac8MRoyA2pWfA0c5A+J28KEJtTRygFFDJ5AlJGSF1wOJDjSOd31OdpCEhWsufVkI/Nc/FoHVE9n0wq9ioeDk9IdItKkEdoZW02c6GBuNVF7R61jBJYHSmbDvXVNrgD0T/VCiemc4vSGUInh8Dgp3/38ZInTRWYDTENVLN3mfI9o2O4r+3WIaGVzJlbyZztfojT4hrQUBkEOTAulOPJJ1UbpazXLZ5eI/CjxrzDwQO66+dx1Dh3dRJlOWvDOoSGHR6A8LxUClXY/jbYvW15czAn18mflCKvTm5k3HVzlfMGQZ+7fnafzI1PuDOeVsdNNjPCtWZwM3nFbqmLmy0rmAY5nynzefPJaNEHuxYzK+leMFWwLm/Ec1JFmEd3VrtIhPnNR/a8WV3kzaugVaprEPr83jJ4w/r4aBVT4iHDhp5Zv0e+3XXp2OQ=
